ribbon:
  eureka:
   enabled: false
beacon:
  ribbon:
    isSecure: true
    listOfServers: https://beacon-network.org:443

feign:
  client:
    config:
      beacon:
        connectTimeout: 30000
        readTimeout: 30000

app:
  batch-size: 3
  thread-pool-size: 4