ribbon:
  eureka:
   enabled: false
beacon:
  ribbon:
    isSecure: true
    listOfServers: https://beacon-network.org:443
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
